### ISSUE TITLE
openvidu-recording-java is broken in Ubuntu 18.04

### ISSUE THREAD

**Issue by ftntming** [OpenVidu/openvidu-tutorials#117]
I've managed to setup the following environment,

1. Ubuntu 18.04
2.  sudo service kurento-media-server status
● kurento-media-server.service - LSB: Kurento Media Server daemon
   Loaded: loaded (/etc/init.d/kurento-media-server; generated)
   Active: active (running) since Sat 2020-07-11 20:10:56 PDT; 30min ago
3. Started openvidu-server as follows,
cd ~/openvidu/openvidu-server
mvn -DDOMAIN_OR_PUBLIC_IP=HOST_LOCAL_IP -DHTTPS_PORT=4443 exec:java
4. Start recording app,
cd ~/openvidu-tutorials/openvidu-recording-java
mvn exec:java
5. Go to https://localhost:5000/
Click Record

Got Error:
Start recording WRONG: HTTP 400 (501)

![image](https://user-images.githubusercontent.com/59328694/87238494-dfd60c80-c3b7-11ea-8d6e-9010f5eae6bd.png)

**Comment by pabloFuente** [comment]
Please, read carefully how to launch openvidu with recording module enabled. OpenVidu Java Client documentation also states what 501 status means (recording module not enabled).

**Comment by ftntming** [comment]
Hi Pablo, wow that's so obvious. I hope the document could add a the "prerequisite" section in the tutorials.

Also I tried the following to enable "recording module" in openvidu-server,

mingli@mingli-virtual-machine:~/openvidu/openvidu-server$ sudo mkdir /recordings
mingli@mingli-virtual-machine:~/openvidu/openvidu-server$ sudo chown -R **kurento** /recordings/
mingli@mingli-virtual-machine:~/openvidu/openvidu-server$ sudo chmod -R 777 /recordings/
mingli@mingli-virtual-machine:~/openvidu/openvidu-server$ cat .env
DOMAIN_OR_PUBLIC_IP=192.168.1.67
OPENVIDU_SECRET=MY_SECRET
HTTPS_PORT=4443
OPENVIDU_RECORDING=true
OPENVIDU_RECORDING_PATH=/recordings/

Error:>

[ERROR] 2020-07-12 10:29:49,592 [io.openvidu.server.OpenViduServer.main()] io.openvidu.server.recording.service.RecordingManager - The recording path "/recordings/" is not valid. Reason: OpenVidu Server does not have write permissions over files created by Kurento Media Server. Try running Kurento Media Server as user "mingli" or run OpenVidu Server as superuser
[ERROR] 2020-07-12 10:29:49,593 [io.openvidu.server.OpenViduServer.main()] io.openvidu.server.recording.service.RecordingManager - Be aware that a folder "/recordings//TEST_RECORDING_PATH_1594574989040" was created and should be manually deleted ("sudo rm -rf /recordings//TEST_RECORDING_PATH_1594574989040")
[ERROR] 2020-07-12 10:29:49,593 [io.openvidu.server.OpenViduServer.main()] io.openvidu.server.recording.service.RecordingManager - Error initializing recording path "/recordings/" set with system property "OPENVIDU_RECORDING_PATH". Shutting down OpenVidu Server

The openvidu-server "think" the /recordings folder is not accessible by kurento, but actually we can see the following 

mingli@mingli-virtual-machine:~/openvidu/openvidu-server$ ls -ltah /recordings/
total 12K
drwxrwxrwx  3 kurento root    4.0K Jul 12 10:29 .
drwxr-xr-x  2 kurento kurento 4.0K Jul 12 10:29 TEST_RECORDING_PATH_1594574989040
drwxr-xr-x 25 root    root    4.0K Jul 12 10:21 ..
mingli@mingli-virtual-machine:~/openvidu/openvidu-server$ ls -ltah /recordings/TEST_RECORDING_PATH_1594574989040/
total 8.0K
drwxr-xr-x 2 kurento kurento 4.0K Jul 12 10:29 .
drwxrwxrwx 3 kurento root    4.0K Jul 12 10:29 ..
-rw-r--r-- 1 kurento kurento    0 Jul 12 10:29 TEST_RECORDING_PATH.webm

Very confused about the permission of openvidu stuff

**Comment by pabloFuente** [comment]
Can I ask why are you trying to run OpenVidu like this? Why using Kurento as a native Ubuntu service and why compiling openvidu-server from scratch?

You have detailed instructions on how to compile and develop OpenVidu in here: https://docs.openvidu.io/en/latest/developing/
If you have problems with paths, just do what the error tells you: **Reason: OpenVidu Server does not have write permissions over files created by Kurento Media Server. Try running Kurento Media Server as user "mingli" or run OpenVidu Server as superuser**
That's pretty clear to me.

**Comment by ftntming** [comment]
> Can I ask why are you trying to run OpenVidu like this? Why using Kurento as a native Ubuntu service and why compiling openvidu-server from scratch?
> 
> You have detailed instructions on how to compile and develop OpenVidu in here: https://docs.openvidu.io/en/latest/developing/
> If you have problems with paths, just do what the error tells you: **Reason: OpenVidu Server does not have write permissions over files created by Kurento Media Server. Try running Kurento Media Server as user "mingli" or run OpenVidu Server as superuser**
> That's pretty clear to me.

I thought KMS is required for openvidu-server to run properly.
e.g. I got the following if I run openvidu-server without KMS
[WARN] 2020-07-14 11:55:17,122 [JsonRpcClient-hearbeatExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClient - [KurentoClient]  Error sending heartbeat to server. Exception: [KurentoClient]  Exception connecting to WebSocket server ws://localhost:8888/kurento

I know about the permission issue with the folder, so I've already tried to either modify the recording folder as "kurento" or "mingli", and further chmod -R to be 777. However the openvidu-server still complains about the permission. anyway, I'm using the workaround to run both KMS and openvidu-server as su

No offense, I'm creating issues in the hope that this could raise some attention and make openvidu more friendly to people who are evaluating it.

**Comment by pabloFuente** [comment]
Sure, I understand. What you want to achieve is perfectly possible and is documented, but you have 2 things going on:

1. You want a development set up of openvidu-server. That's fine. Of course, you need KMS running in your machine. But the official supported way is different that what you are doing. It is described here: https://docs.openvidu.io/en/latest/developing/#example-setup-for-development. As you can see, you are supposed to run Kurento with docker: https://docs.openvidu.io/en/2.15.0/developing/#running-kms, not as a native service. Precisely because this are common problems that arise when doing so.
2. If you still want to run KMS as a native Ubuntu service, then you must do what the error is saying. It has nothing to do with the recording folder permissions. You are probably by now give every possible permission to that folder. The problem is that **KMS is creating files inside that folder with higher permissions that what openvidu can manage**. The problem is that te user running openvidu-server is different (and with less perimssions) than the user running KMS. If you run KMS with `sudo service kurento-media-server`, then no matter the permissions of the recording folder, the files created by KMS inside of it won't be manageable by openvidu-server. As the error message say, you must run KMS with the same user as openvidu-server (try `/usr/bin/kurento-media-server`, or openvidu-server with sudo. You choose.
