### ISSUE TITLE
Demos on aws

### ISSUE THREAD

**Issue by ValSbo** [OpenVidu/openvidu-tutorials#28]
### Hello everyone, i am trying to deploying Openvidu Demos on AWS, i imported my selfsigned certificate following the tutorial https://openvidu.io/docs/deployment/deploying-demos-aws/ but i am not able to connect on https. Clicking on the Output link i have an "accept-certificate" error.

What's wrong? Am i avoiding some steps to run the demos? What can i do after deploying demos on AWS?

Thank you for your answers.

**Comment by pabloFuente** [comment]
If you use self-signed certificates of course you will get an invalid-certificate warning in the browser. To avoid it you must use a valid certificate. You'll need:
- A domain name
- Link your domain name to the AWS Elastic IP you indicate in the template, through your DNS hosting provider.
- Then you can choose whether to let OpenVidu automatically create a valid certificate with Let's Encrypt or to use your own certificate (columns blue and yellow respectively in the doc page you linked).

**Comment by tibinvpaul** [comment]
Hey @pabloFuente - I have set it up with a SUB domain and an Elastic IP after choosing letsencrypt as certificate type. The domain is accessible and I am able to login to the openvidu interface. I am still getting the SSL warning in the browser and when I test the connection, seeing `net::ERR_CERT_AUTHORITY_INVALID` error in the browser console. Do I need to do any steps other than listed under https://openvidu.io/docs/deployment/deploying-aws?

Thanks.

**Comment by pabloFuente** [comment]
Are you able to connect to OpenVidu Server dashboard through `https://YOUR.SUBDOMAIN.YOUR.DOMAIN.com:4443/`? And does the green lock appear in the browsers navbar, indicating that it is a secure web?

**Comment by tibinvpaul** [comment]
I am able to connect and login to the dashboard. The green lock is not appearing but `Not Secure` label is coming instead. I will outline the steps I have done.

1. My initial configuration was `selfsigned` since I didn't have an Elastic IP.
2. After the first set up has completed, I updated the stack and added let's encrypt certificate, elastic IP and FQDN. The status is `UPDATE_COMPLETE.
3. My domain is in Digital Ocean and pointed the subdomain to the elastic IP.
4. I am able to access the dashboard with `Not Secure` label.

**Comment by tibinvpaul** [comment]
@ValSbo closed this but any help will be appreciated @pabloFuente.
