### ISSUE TITLE
Ionic /api/sessions error code 0

### ISSUE THREAD

**Issue by mujahidmasood** [OpenVidu/openvidu-tutorials#94]
Hello,

I am trying to integrate OpenVidu in Ionic app. I am following official tutorial.
Few days ago I was able to make it work with demo link `https://demos.openvidu.io:4443` .

But somehow its not working with demo link as well as local docker deployment.
[https://docs.openvidu.io/en/2.13.0/tutorials/openvidu-ionic/](url)
 
I am getting the errors below.

<img width="302" alt="Screenshot 2020-04-27 at 01 42 52" src="https://user-images.githubusercontent.com/1822007/80323119-b6322e00-8829-11ea-8275-471e5fba84a0.png">

<img width="612" alt="Screenshot 2020-04-27 at 01 43 33" src="https://user-images.githubusercontent.com/1822007/80323121-b8948800-8829-11ea-9535-b98a987ce9fa.png">

Strange thing is POST request works fine with Intellij Restful Service
`POST https://192.168.1.112:4443/api/sessions
Content-Type: application/json
Authorization: Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU

{   "mediaMode": "ROUTED",   "recordingMode": "MANUAL",   "defaultOutputMode": "COMPOSED",   "defaultRecordingLayout": "BEST_FIT" }
`

**Comment by marceth** [comment]
I am having similar problems with the version 2.13
Last week I ran the insecure-js tutorial with OpenVidu Server 2.12 and it worked fine in Google Chrome.
Today I've pulled the new commits from the repo and ran the 2.13 docker image. It still works in Firefox but in Chrome the Webcam does not work.
I've also tried https://demosopenstack.openvidu.io/ and there I'm getting the same Error.

Javascript logs from https://demosopenstack.openvidu.io
![image](https://user-images.githubusercontent.com/29308357/80357862-e1de0400-887b-11ea-81a8-6804ff22623f.png)

**Comment by pabloFuente** [comment]
Please, update openvidu-browser to 2.13.0

**Comment by mujahidmasood** [comment]
> Please, update openvidu-browser to 2.13.0
It is updated to 2.13.0

**Comment by marceth** [comment]
I have done that with the tutorial but I am getting the same error.
I did not see that https://demosopenstack.openvidu.io still runs on version 2.12
Then maybe it is not an issue with 2.13... 

Error from the js tutorial example run localy with version 2.13.
![image](https://user-images.githubusercontent.com/29308357/80358694-19997b80-887d-11ea-8d89-09fba6317528.png)

**Comment by pabloFuente** [comment]
This is working fine in Chrome in all our development and testing environments, bot for Chrome desktop in multiple OSs and Chrome mobile for Android. This error is triggered by Web API navigator.mediaDevice.getUserMedia. It usually happens when Chrome does not have acces to the webcam or microphone for any reason (another process owns the device at the moment, audio drivers are not working fine....).

Try accessing only the webcam and only the microphone in other webpage to see if the error is triggered by one device or the other.

**Comment by marceth** [comment]
> This is working fine in Chrome in all our development and testing environments, both for Chrome desktop in multiple OSs and Chrome mobile for Android. This error is triggered by Web API navigator.mediaDevice.getUserMedia. It usually happens when Chrome does not have acces to the webcam or microphone for any reason (another process owns the device at the moment, audio drivers are not working fine....).
> 
> Try accessing only the webcam and only the microphone in other webpage to see if the error is triggered by one device or the other.

Thank you for your answer.
Since the webcam was not working, I've only tested the webcam which worked on https://webrtc.github.io/samples/src/content/getusermedia/gum/
But actually my problem was the microphone not the webcam and since the microphone did not work, the webcam didn't either. With a working microphone both https://demosopenstack.openvidu.io/ and the insecure-js tutorial work.
It would be great if the webcam would work even when there is a problem with the microphone. Which seems to be the case in Firefox but not in Chrome with my setup.
Anyway, thanks again for your quick reply!

**Comment by mujahidmasood** [comment]
I have tried it on Android device, Firefox and chrome.
Video seems to stream fine (I could see camera and mic work fine). 
When I send /api/sessions and /api/tokens request in the response I am getting the issues in images.

@marceth No problems ;)

**Comment by mujahidmasood** [comment]
Strange thing is 
[https://192.168.2.1:4443/dashboard/](url) works fine on chrome, android browser and firefox.
But when I use it in ionic app the same url, it gives me the error.

**Comment by mujahidmasood** [comment]
It was problems with permissions, I was not adding permission for bluetooth.
But the error message is misleading.

**Comment by pabloFuente** [comment]
The error message is the best we can do. We are not generating that error message: that is what the browser natively returns.
